# Copyright (c) 2015, Google Inc. Please see the AUTHORS file for details.
# All rights reserved. Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

install:
  - cinst -y dart-sdk
  - set PATH=%PATH%;C:\tools\dart-sdk\bin
  - set PATH=%PATH%;%APPDATA%\Pub\Cache\bin
  - pub get

build: off

test_script:
  - pub global activate tuneup
  - pub global run tuneup check --ignore-infos
  - dart test\all.dart
  - dart tool\grind.dart analyze-init

cache:
  - C:\Users\appveyor\AppData\Pub\Cache
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
