name: grinder
version: 0.0.6
author: Devon Carew <devoncarew@google.com>
description: Grinder - a task based, dependency aware build system.
homepage: https://github.com/google/grinder.dart
dependencies:
  args: any
dev_dependencies:
  unittest: any
