name: grinder
version: 0.6.5-dev

description: Grinder - a task based, dependency aware build system.
homepage: https://github.com/google/grinder.dart
author: Devon Carew <devoncarew@google.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: '>=0.10.0 <0.13.0'
  quiver: '>=0.18.0 <0.21.0'

dev_dependencies:
  unittest: any

executables:
  grind:
  grinder:
